services:
  dev:
    container_name: ros-devel
    image: ros-devel
    build:
      context: ./Docker
    environment:
      - TERM=xterm-256color
      - LIDAR_TYPE=x2
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./colcon_ws:/home/turtle/colcon_ws
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/ydlidar:/dev/ydlidar
      - /dev/ydlidar:/dev/ttyUSB1
      - /dev/arduino:/dev/arduino
      - /dev/arduino:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    ports:
      - "11311:11311"
      - "11345:11345"
      - "11356:11356"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

