networks:
  ros-bridge:
    name: ros-bridge
    driver: bridge
  
services:
  dev:
    container_name: ros-devel
    image: ros-devel
    build:
      context: ./Docker
    environment:
      - TERM=xterm-256color
      - LIDAR_TYPE=x2
    volumes:
      - ./colcon_ws:/home/ros/colcon_ws
    devices:
      - /dev/gpiomem0:/dev/gpiomem0
      - /dev/gpiomem1:/dev/gpiomem1
      - /dev/gpiomem2:/dev/gpiomem2
      - /dev/gpiomem3:/dev/gpiomem3
      # - /dev/ydlidar:/dev/ydlidar
      # - /dev/arduino:/dev/arduino
      # - /dev/arduino:/dev/ttyUSB0
    ports:
      - "11311:11311"
      - "11345:11345"
      - "11356:11356"
    networks:
      - ros-bridge
    stdin_open: true
    tty: true

