services:
  dev:
    container_name: ros-devel
    image: ros-devel
    build:
      context: ./Docker
    environment:
      - TERM=xterm-256color
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./colcon_ws:/home/turtle/colcon_ws
    devices:
      - /dev/ydlidar:/dev/ydlidar:rw
      - /dev/arduino:/dev/arduino:rw
      - /dev/gpiochip0:/dev/gpiochip0:rw
      - /dev/gpiochip1:/dev/gpiochip1:rw

    # ports: # not necessary with network_mode: host
    #   - "11311:11311"
    #   - "11345:11345"
    #   - "11356:11356"
    #   - "8080:8080"
    network_mode: host
    runtime: nvidia
    # privileged: true
    stdin_open: true
    tty: true
