services:
  dev:
    container_name: humble
    image: ros-dev:humble
    build:
      context: ./Docker
      dockerfile: ./humble.dockerfile
      args:
        - ROS_ARCH=$ROS_ARCH
    environment:
      - TERM=xterm-256color
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
      - LIDAR_TYPE=x2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./colcon_ws:/home/humble/colcon_ws
      - .gazebo:/home/gazebo/.gazebo
    devices:
      - dev/dri:/dev/dri
      - /dev/ydlidar:/dev/ydlidar # run /scripts/udev.sh in host first
      - /dev/ydlidar:/dev/ttyUSB0
      # - /dev/arduino:/dev/arduino
    network_mode: host
    stdin_open: true
    tty: true
    runtime: nvidia