controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dogbot_base_controller:
      type: dogbot_drive_controller/DogBotDriveController

    # dogbot_servo_controller:
    #   type: dogbot_servo_controller/DogBotServoController

dogbot_base_controller:
  ros__parameters:
    lf_wheel_name: "lf_wheel_joint"
    rf_wheel_name: "rf_wheel_joint"
    lb_wheel_name: "lb_wheel_joint"
    rb_wheel_name: "rb_wheel_joint"

    wheel_separation_x: 0.21
    wheel_separation_y: 0.17

    wheel_radius: 0.04

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    cmd_vel_timeout: 0.5
    velocity_rolling_window_size: 10
    publish_rate: 50.0


# dogbot_servo_controller:
#   ros__parameters:
#     servo_gripper_name: "servo_gripper_joint"
#     servo_forearm_name: "servo_forearm_joint"
#     servo_shoulder_name: "servo_shoulder_joint"


