// Copyright 2024 Long Liangmao
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Author: Bence Magyar, Enrique Fernández, Manuel Meraz
 */

#ifndef DOGBOT_ARM_CONTROLLER_DOGBOT_ARM_CONTROLLER_HPP_
#define DOGBOT_ARM_CONTROLLER_DOGBOT_ARM_CONTROLLER_HPP_

#include <chrono>
#include <cmath>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "hardware_interface/handle.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_box.h"
#include "realtime_tools/realtime_buffer.h"
#include "realtime_tools/realtime_publisher.h"

// auto-generated by generate_parameter_library
#include "dogbot_arm_controller_parameters.hpp"

namespace dogbot_arm_controller {
    class DogBotArmController : public controller_interface::ControllerInterface {

    public:
        DOGBOT_ARM_CONTROLLER_PUBLIC
        DogBotArmController();

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::InterfaceConfiguration command_interface_configuration() const override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::InterfaceConfiguration state_interface_configuration() const override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::return_type update(
                const rclcpp::Time &time, const rclcpp::Duration &period) override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_init() override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_configure(
                const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_activate(
                const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_deactivate(
                const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_cleanup(
                const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_error(
                const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_ARM_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_shutdown(
                const rclcpp_lifecycle::State &previous_state) override;

    protected:
        struct ServoHandle {
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> position;
        };

        controller_interface::CallbackReturn configure_servo(const std::string &servo_name);

        std::map<std::string, ServoHandle> registered_handles_;

        // Parameters from ROS
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;

        // Timeout to consider cmd_vel commands old
        std::chrono::milliseconds cmd_vel_timeout_{500};

        std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_ = nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
                realtime_odometry_publisher_ = nullptr;

        std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_ =
                nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
                realtime_odometry_transform_publisher_ = nullptr;

        bool subscriber_is_active_ = false;
        rclcpp::Subscription<Twist>::SharedPtr velocity_command_subscriber_ = nullptr;
        
        realtime_tools::RealtimeBox<std::shared_ptr<Twist>> received_velocity_msg_ptr_{nullptr};

        rclcpp::Time previous_update_timestamp_{0};

        // publish rate limiter
        double publish_rate_ = 50.0;
        rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
        rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};

        bool is_halted_ = false;

        void reset();

        void halt();
    };
} // namespace dogbot_arm_controller
#endif // DOGBOT_ARM_CONTROLLER_DOGBOT_ARM_CONTROLLER_HPP_
