// Copyright 2024 Long Liangmao
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef DOGBOT_SERVO_CONTROLLER_DOGBOT_SERVO_CONTROLLER_HPP_
#define DOGBOT_SERVO_CONTROLLER_DOGBOT_SERVO_CONTROLLER_HPP_

#include <chrono>
#include <cmath>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "dogbot_servo_controller/visibility_control.h"
#include "dogbot_interfaces/msg/servo_position.hpp"
#include "hardware_interface/handle.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_box.h"
#include "realtime_tools/realtime_buffer.h"
#include "realtime_tools/realtime_publisher.h"

// auto-generated by generate_parameter_library
#include "dogbot_servo_controller_parameters.hpp"

namespace dogbot_servo_controller
{
    using ServoPosition = dogbot_interfaces::msg::ServoPosition;

    class DogBotServoController : public controller_interface::ControllerInterface
    {

    public:
        DOGBOT_SERVO_CONTROLLER_PUBLIC
        DogBotServoController();

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::InterfaceConfiguration command_interface_configuration() const override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::InterfaceConfiguration state_interface_configuration() const override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::return_type update(
            const rclcpp::Time &time, const rclcpp::Duration &period) override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_init() override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_configure(
            const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_activate(
            const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_deactivate(
            const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_cleanup(
            const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_error(
            const rclcpp_lifecycle::State &previous_state) override;

        DOGBOT_SERVO_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_shutdown(
            const rclcpp_lifecycle::State &previous_state) override;

    protected:
        struct ServoHandle
        {
            std::reference_wrapper<const hardware_interface::LoanedStateInterface> feedback;
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> position;
        };
        controller_interface::CallbackReturn configure_servo(const std::string &servo_name);
        std::map<std::string, ServoHandle> registered_handles_;

        std::shared_ptr<ParamListener> param_listener_;
        Params params_;

        bool subscriber_is_active_ = false;
        rclcpp::Subscription<ServoPosition>::SharedPtr position_command_subscriber_ = nullptr;
        realtime_tools::RealtimeBox<std::shared_ptr<ServoPosition>> received_position_msg_ptr_{nullptr};

        double publish_rate_ = 50.0;
        rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
        rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};

        bool is_halted_ = false;
        void reset();
        void halt();
    };
} // namespace dogbot_servo_controller
#endif // DOGBOT_SERVO_CONTROLLER_DOGBOT_SERVO_CONTROLLER_HPP_
